version: "3.9"

services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: revseq-dashboard
    ports:
      - "8000:8000"
    environment:
      - NEXTSTRAIN_BASE_URL=${NEXTSTRAIN_BASE_URL:-http://127.0.0.1:4000}
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  nextstrain:
    build:
      context: .
      dockerfile: Dockerfile_nextstrain
    container_name: revseq-nextstrain
    ports:
      - "4000:4000"
    environment:
      - HOST=0.0.0.0
    command: ["npx", "auspice-revseq", "view", "--datasetDir", "dashboard/static/auspice"]
